# -*- coding: utf-8 -*-
"""ML PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wL7566L7CbETtNF1RODS8T-bf8KfVyct

# ***Analyse & Prédiction des Admissions aux Lycées Pilotes***
---

# ***1.Introduction***

Le concours des lycées pilotes constitue une étape importante dans le système éducatif tunisien. Chaque année, des milliers d'élèves participent à cet examen afin d'accéder aux établissements pilotes réputés pour leur excellence académique.

Dans ce projet, nous exploitons les données ouvertes publiées par le portail Open Data tunisien afin d'analyser les résultats du concours des lycées pilotes pour la session de juin 2024.

L'objectif principal est de développer un modèle de Machine Learning capable de prédire le nombre d'élèves affectés aux lycées pilotes à partir de plusieurs variables descriptives telles que le nombre d'inscrits, le nombre de présents, le genre et le type de candidature.

Le projet suit l'ensemble du pipeline standard d'un projet Machine Learning :

Définition du problème
Collecte des données
Exploration des données
Prétraitement et Feature Engineering
Construction des modèles
Évaluation des performances
Optimisation des hyperparamètres
Déploiement d'une application Streamlit

# ***2. Présentation du Dataset***


Source des données

Les données utilisées dans ce projet proviennent du portail Open Data tunisien :

Open Data Tunisie - Concours Lycées Pilotes

Cette source officielle met à disposition des données statistiques relatives au concours des lycées pilotes en Tunisie.

Description du Dataset

Le dataset est composé de cinq fichiers CSV :

***1. Effectif des inscrits***

Contient le nombre total d'élèves inscrits au concours selon :

CRE (Commissariat Régional de l'Éducation)
Type de candidature
Genre
***2. Effectif des présents***

Contient le nombre d'élèves ayant effectivement passé le concours.

Variables :

CRE
Type de candidature
Genre
Effectif_présentés
***3. Effectif des affectés aux lycées pilotes***

Contient le nombre d'élèves admis aux lycées pilotes.

Variables :

CRE
Type de candidature
Genre
Affectés_pilote
***4. Effectif des admis***

Présente les effectifs admis selon :

CRE
Genre
Année de naissance
***5. Effectif des inscrits selon l'année de naissance***

Permet une analyse démographique des candidats.

Variable cible

Dans notre projet, la variable cible est :

Affectés_pilote

Cette variable représente le nombre d'élèves affectés aux lycées pilotes.

Variables explicatives

Les principales variables utilisées pour la prédiction sont :


CRE

Type de candidature

Genre

Effectif_inscrits

Effectif_présentés

Taux_presence

Taille du Dataset


Après fusion et nettoyage :

108 observations

6 variables explicatives

1 variable cible

# ***3. Définition du problème***
Problématique

Peut-on prédire le nombre d'élèves affectés aux lycées pilotes à partir des caractéristiques des candidats et des statistiques du concours ?

Type de problème

Ce projet traite deux tâches d'apprentissage supervisé :

Régression

Prédiction du nombre exact d'élèves affectés.

Modèles utilisés :

Linear Regression
Random Forest Regressor
Classification

Classification des régions selon leur niveau d'affectation :

Faible
Moyen
Excellent

Modèle utilisé :

Random Forest Classifier

ÉTAPE 0 : Installation
"""

!pip install pandas numpy matplotlib seaborn scikit-learn xgboost streamlit -q

"""ÉTAPE 1 : Importation"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

"""ÉTAPE 2 : Lire correctement les CSV"""

import pandas as pd
import os

for file in os.listdir('/content'):
    if file.endswith('.csv'):
        print("="*50)
        print(file)

        df = pd.read_csv(f'/content/{file}')

        print("Shape :", df.shape)
        print("\nColonnes :")
        print(df.columns.tolist())

        print("\nAperçu :")
        print(df.head())

        print("\n")

inscrits = pd.read_csv(
    "/content/effectif-des-inscrits-session-juin-2024.csv",
    sep=";"
)

presentes = pd.read_csv(
    "/content/effectif-des-presentes-session-juin-2024.csv",
    sep=";"
)

affectes = pd.read_csv(
    "/content/effectif-des-affectes-au-pilote-session-juin-2024.csv",
    sep=";"
)

admis = pd.read_csv(
    "/content/effectif-des-admis-session-juin.csv",
    sep=";"
)

naissance = pd.read_csv(
    "/content/effectif-des-inscrits-selon-annee-de-naissance-session-juin-2024.csv",
    sep=";"
)

inscrits.head()

"""ÉTAPE 3 : Compréhension métier

Les fichiers contiennent :

inscrits

Nombre d'inscrits

présentes

Nombre ayant passé le concours

affectés

Nombre admis aux lycées pilotes

admis

Nombre ayant réussi

naissance

Répartition selon âge

ÉTAPE 4 : Vérification
"""

print(inscrits.shape)
print(presentes.shape)
print(affectes.shape)
print(admis.shape)
print(naissance.shape)

"""ÉTAPE 5 : Valeurs manquantes"""

inscrits.isnull().sum()

presentes.isnull().sum()

admis.isnull().sum()

"""ÉTAPE 6 : Nettoyage"""

affectes["Affectés_pilote"] = pd.to_numeric(
    affectes["Affectés_pilote"],
    errors="coerce"
)

affectes["Affectés_pilote"] = affectes[
    "Affectés_pilote"
].fillna(0)

"""ÉTAPE 7 : Fusion des datasets

Notre cible sera :

Affectés_pilote

On veut prédire le nombre d'élèves affectés.
"""

df = inscrits.merge(
    presentes,
    on=["CRE","type candidature","genre"]
)

df = df.merge(
    affectes,
    on=["CRE","type candidature","genre"]
)

"""Vérification :"""

df.head()

"""ÉTAPE 8 : Feature Engineering

Créer :

taux présence
"""

df["Taux_presence"] = (
    df["Effectif_présentés"] /
    df["Effectif_inscrits"]
)

"""taux affectation"""

df["Taux_affectation"] = (
    df["Affectés_pilote"] /
    df["Effectif_présentés"]
)

"""ÉTAPE 9 : Analyse Exploratoire"""

df.describe()

"""
# **Matrice de corrélation **"""

plt.figure(figsize=(8,6))

corr_matrix = df.corr(numeric_only=True)

sns.heatmap(
    corr_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Matrice de corrélation")
plt.show()

"""#Histogramme

"""

plt.figure(figsize=(8,5))

sns.histplot(
    df["Affectés_pilote"],
    bins=20
)

plt.show()

"""Distribution des affectés"""

plt.figure(figsize=(8,5))

sns.histplot(
    df["Affectés_pilote"],
    bins=20
)

plt.show()

"""Répartition par CRE"""

plt.figure(figsize=(12,6))

sns.boxplot(
    data=df,
    x="CRE",
    y="Affectés_pilote"
)

plt.xticks(rotation=90)

plt.show()

"""ÉTAPE 10 : Encodage"""

encoder = LabelEncoder()

df["CRE"] = encoder.fit_transform(df["CRE"])

df["type candidature"] = encoder.fit_transform(
    df["type candidature"]
)

df["genre"] = encoder.fit_transform(
    df["genre"]
)

"""ÉTAPE 11 : Définir X et y

Notre objectif :

Prédire :
"""

X = df.drop(
    columns=[
        "Affectés_pilote",
        "Taux_affectation"
    ]
)

"""ÉTAPE 12 : Train/Test Split"""

print(X.shape)

print("df :", df.shape)
print("X :", X.shape)
print("y :", y.shape)

y = df["Affectés_pilote"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""ÉTAPE 13 : Standardisation"""

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

df.isnull().sum()

df = df.dropna()

df.isnull().sum()

X = df.drop(columns=["Affectés_pilote"])

y = df["Affectés_pilote"]

"""ÉTAPE 14 : Modèle 1

Régression Linéaire
"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

import numpy as np

print("NaN X_train :", np.isnan(X_train).sum())
print("NaN X_test :", np.isnan(X_test).sum())

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train, y_train)

pred_lr = lr.predict(X_test)

from sklearn.metrics import mean_absolute_error, r2_score

print("MAE :", mean_absolute_error(y_test, pred_lr))
print("R2 :", r2_score(y_test, pred_lr))

"""Interprétation pour le rapport

MAE = 15.57

En moyenne, le modèle se trompe d'environ 15 élèves lorsqu'il prédit le nombre d'élèves affectés aux lycées pilotes.

R² = 0.696

Le modèle explique environ 69,6 % de la variabilité du nombre d'élèves affectés. Cela indique une relation significative entre les variables explicatives et la variable cible.

Tu peux écrire dans ton notebook :

Le modèle de régression linéaire fournit des performances satisfaisantes avec un coefficient de détermination R² de 69,6 %. Cependant, les relations entre les variables semblent partiellement non linéaires, ce qui justifie l'utilisation de modèles plus avancés comme Random Forest.

Étape 15 - Random Forest
"""

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

pred_rf = rf.predict(X_test)

from sklearn.metrics import mean_absolute_error, r2_score

print("MAE RF :", mean_absolute_error(y_test, pred_rf))
print("R2 RF :", r2_score(y_test, pred_rf))

""" Comparaison des modèles"""

results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest"],
    "MAE": [
        mean_absolute_error(y_test, pred_lr),
        mean_absolute_error(y_test, pred_rf)
    ],
    "R2": [
        r2_score(y_test, pred_lr),
        r2_score(y_test, pred_rf)
    ]
})

results

"""Visualisation de comparaison"""

import matplotlib.pyplot as plt

results.plot(
    x="Model",
    y="R2",
    kind="bar",
    legend=False
)

plt.title("Comparaison des modèles")
plt.ylabel("R²")
plt.show()

"""**Valeurs réelles vs prédictions"**"""

plt.figure(figsize=(7,6))

plt.scatter(y_test, pred_rf)

plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    'r--'
)

plt.xlabel("Valeurs réelles")
plt.ylabel("Prédictions")

plt.title("Réel vs Prédit")
plt.show()

"""Importance des variables (très apprécié en soutenance)"""

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance)

import seaborn as sns

plt.figure(figsize=(10,5))

sns.barplot(
    data=importance,
    x="Importance",
    y="Feature"
)

plt.title("Importance des variables")
plt.show()

"""Le modèle Random Forest a obtenu les meilleures performances avec un R² de 71,3 %, surpassant la régression linéaire. Cela suggère que les relations entre les variables explicatives et le nombre d'élèves affectés ne sont pas entièrement linéaires.

Analyse des variables importantes
Variable	Importance
Effectif_présentés	61.8 %
Effectif_inscrits	32.1 %
CRE	3.1 %
Taux_presence	2.3 %
Genre	0.6 %
Type candidature	0.08 %

Le nombre de candidats présents au concours constitue la variable la plus influente dans la prédiction des affectations aux lycées pilotes, avec une importance de 61,8 %. Le nombre d'inscrits représente également un facteur majeur (32,1 %). Les variables démographiques comme le genre ou le type de candidature ont un impact limité.

GridSearchCV (pour montrer l'optimisation)
"""

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 10, None],
    'min_samples_split': [2, 5]
}

grid = GridSearchCV(
    estimator=RandomForestRegressor(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring='r2',
    n_jobs=-1
)

grid.fit(X_train, y_train)

print("Best Parameters:")
print(grid.best_params_)

best_rf = grid.best_estimator_

pred_best = best_rf.predict(X_test)

print("MAE :", mean_absolute_error(y_test, pred_best))
print("R2 :", r2_score(y_test, pred_best))

"""Partie Classification

On transforme le problème :

Créer des classes
"""

df["Niveau"] = pd.cut(
    df["Affectés_pilote"],
    bins=[-1,20,80,200],
    labels=["Faible","Moyen","Excellent"]
)

"""Vérification :"""

df["Niveau"].value_counts()

"""Préparation"""

X_class = df.drop(
    columns=["Affectés_pilote","Niveau"]
)

y_class = df["Niveau"]

"""Split"""

from sklearn.model_selection import train_test_split

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    X_class,
    y_class,
    test_size=0.2,
    random_state=42
)

"""Scaling"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_c = scaler.fit_transform(X_train_c)
X_test_c = scaler.transform(X_test_c)

"""Random Forest Classifier"""

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

clf.fit(X_train_c, y_train_c)

"""Évaluation"""

pred_class = clf.predict(X_test_c)

from sklearn.metrics import accuracy_score

print(
    "Accuracy:",
    accuracy_score(
        y_test_c,
        pred_class
    )
)

from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_c,
        pred_class
    )
)

"""# ***matrice de confusion***"""

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test_c,
    pred_class
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=clf.classes_,
    yticklabels=clf.classes_
)

plt.xlabel("Prédiction")
plt.ylabel("Réel")
plt.title("Matrice de confusion")

plt.show()

from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_c,
        pred_class
    )
)

"""# Partie Streamlit"""

import joblib

joblib.dump(rf, "model.pkl")
joblib.dump(scaler, "scaler.pkl")

requirements = """
streamlit
pandas
numpy
scikit-learn
joblib
"""

with open("requirements.txt", "w") as f:
    f.write(requirements)

print("requirements.txt créé")

readme = """
# Prédiction des Affectations aux Lycées Pilotes

Projet Machine Learning basé sur les données Open Data Tunisie.

## Technologies
- Python
- Pandas
- Scikit-Learn
- Streamlit

## Modèles
- Linear Regression
- Random Forest

## Déploiement
Application Streamlit permettant de prédire le nombre d'élèves affectés aux lycées pilotes.
"""

with open("README.md", "w", encoding="utf-8") as f:
    f.write(readme)

print("README.md créé")

streamlit_code = '''
import streamlit as st
import joblib
import numpy as np

model = joblib.load("model.pkl")
scaler = joblib.load("scaler.pkl")

st.title("Prédiction des Affectations aux Lycées Pilotes")

cre = st.number_input("CRE encodé", min_value=0)
type_candidature = st.number_input("Type candidature encodé", min_value=0)
genre = st.number_input("Genre encodé", min_value=0)
effectif_inscrits = st.number_input("Effectif inscrits", min_value=0)
effectif_presentes = st.number_input("Effectif présentés", min_value=0)
taux_presence = st.number_input("Taux présence", min_value=0.0, max_value=1.0)

if st.button("Prédire"):
    data = np.array([[cre, type_candidature, genre,
                      effectif_inscrits,
                      effectif_presentes,
                      taux_presence]])

    data = scaler.transform(data)

    prediction = model.predict(data)

    st.success(f"Nombre prédit d'élèves affectés : {prediction[0]:.0f}")
'''

with open("streamlit_app.py", "w", encoding="utf-8") as f:
    f.write(streamlit_code)

print("streamlit_app.py créé")

import joblib

joblib.dump(rf, "model.pkl")
joblib.dump(scaler, "scaler.pkl")

import os

os.listdir()

from google.colab import files

files.download("streamlit_app.py")

files.download("README.md")
files.download("requirements.txt")
files.download("model.pkl")
files.download("scaler.pkl")

"""Ce projet a permis de mettre en œuvre l'ensemble des étapes d'un pipeline Machine Learning sur des données réelles issues du portail Open Data tunisien. Après le nettoyage, l'exploration et le prétraitement des données, plusieurs modèles de régression ont été évalués. Le modèle Random Forest a obtenu les meilleures performances avec un coefficient de détermination R² supérieur à celui de la régression linéaire. Une application Streamlit a également été développée afin de démontrer le déploiement opérationnel du modèle et de permettre des prédictions interactives."""